### PR TITLE
logs and permissions for sending emails

### LINKED ISSUE #82: check if email send works

### PR DESCRIPTION
**Pull request by IAfanasovMob**
Closes #82

### CODE REVIEW

**Comment by ghost** [comment]
which function need policies for SES ?
Ideally, we should create a separate role for this function and include all required policies (logs, ses, dynamodb) - POLP.

**Comment by IAfanasovMob** [comment]
> which function need policies for SES ?
> Ideally, we should create a separate role for this function and include all required policies (logs, ses, dynamodb) - POLP.

Agree. Looking into current policies I thought we planned to do it after MVP because of all the functions have DynamoDB write access and for sure not all of them needed. Is it proper to do the quick solution now and review all the AIM policies later?

**Comment by ghost** [comment]
> > which function need policies for SES ?
> > Ideally, we should create a separate role for this function and include all required policies (logs, ses, dynamodb) - POLP.
> 
> Agree. Looking into current policies I thought we planned to do it after MVP because of all the functions have DynamoDB write access and for sure not all of them needed. Is it proper to do the quick solution now and review all the AIM policies later?

That is why I said 'ideally'.
 Definitely we should take care of IAM policies after MVP.

One remark - not all of them have access to writing dynamoDb.
The only part that is missing some functions, for example, has permissions to do 'update, put' call but they need only 'put'...

**Comment by IAfanasovMob** [comment]
> That is why I said 'ideally'.
> Definitely we should take care of IAM policies after MVP.

https://github.com/I-OWE-YOU/aws-backend/issues/91

**Pull request merged**
